name: dart_script
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: ">=2.9.3 <3.0.0"

dependencies:
  http: ^0.12.2
  args: ^1.6.0
  path: ^1.7.0
  
dev_dependencies:
  pedantic: ^1.9.0
